In [3]:
import math

def sigmoid(x):                 
  op = 1 / (1 + math.exp(-x))
  return op

def relu(x):                    
  op = max(0,x)
  return op

def tanh(x):                    
  op = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
  return op

x = int(input("Enter Input: "))

print("Sigmoid: ", sigmoid(x))
print("Relu: ", relu(x))
print("Tanh: ", tanh(x))


Enter Input: 2
Sigmoid:  0.8807970779778823
Relu:  2
Tanh:  0.964027580075817


In [6]:
import numpy as np

class Neuron:
  def __init__(self, num_inputs, activation_function):
    self.weights = np.random.rand(num_inputs)
    self.bias = np.random.rand()
    self.activation_function = activation_function

  def activate(self, inputs):
    weighted_sum = np.dot(self.weights, inputs) + self.bias
    output = self.activation_function(weighted_sum)
    return output

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return max(0, x)

def tanh(x):
  return np.tanh(x)

neuron_sigmoid = Neuron(3, sigmoid)
neuron_relu = Neuron(3, relu)
neuron_tanh = Neuron(3, tanh)

inputs = np.array([0.5, 0.2, 0.8])

output_sigmoid = neuron_sigmoid.activate(inputs)
output_relu = neuron_relu.activate(inputs)
output_tanh = neuron_tanh.activate(inputs)

print("Output (Sigmoid):", output_sigmoid)
print("Output (ReLU):", output_relu)
print("Output (Tanh):", output_tanh)

Output (Sigmoid): 0.7641300892522849
Output (ReLU): 1.3604398615273876
Output (Tanh): 0.7889363584575122


In [7]:
# Implementation of XOR Gate

import numpy as np

class Neuron:
  def __init__(self, weights, bias, activation_function):
    self.weights = weights
    self.bias = bias
    self.activation_function = activation_function

  def activate(self, inputs):
    weighted_sum = np.dot(self.weights, inputs) + self.bias
    output = self.activation_function(weighted_sum)
    return output

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return max(0, x)

def xor_network(input1, input2):
  h1 = Neuron(np.array([1, 1]), -1, relu)
  h2 = Neuron(np.array([-1, 1]), 0, relu)
  output_neuron = Neuron(np.array([1, -1]), 1, sigmoid)

  hidden_output1 = h1.activate(np.array([input1, input2]))
  hidden_output2 = h2.activate(np.array([input1, input2]))
  final_output = output_neuron.activate(np.array([hidden_output1, hidden_output2]))
  return final_output

input1 = int(input("Enter input 1 (0 or 1): "))
input2 = int(input("Enter input 2 (0 or 1): "))

output = xor_network(input1, input2)
print(f"Input: {input1}, {input2}, Output: {output}")

Enter input 1 (0 or 1): 1
Enter input 2 (0 or 1): 0
Input: 1, 0, Output: 0.7310585786300049


In [8]:
# Implementation of XOR gate where hidden layers has RELU and tanh and output layer has Sigmoid

import numpy as np

class Neuron:
  def __init__(self, weights, bias, activation_function):
    self.weights = weights
    self.bias = bias
    self.activation_function = activation_function

  def activate(self, inputs):
    weighted_sum = np.dot(self.weights, inputs) + self.bias
    output = self.activation_function(weighted_sum)
    return output

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def relu(x):
  return max(0, x)

def tanh(x):
  return np.tanh(x)

def xor_network(input1, input2):
  h1 = Neuron(np.array([1, 1]), -1, relu)
  h2 = Neuron(np.array([-1, 1]), 0, tanh)
  output_neuron = Neuron(np.array([1, -1]), 1, sigmoid)

  hidden_output1 = h1.activate(np.array([input1, input2]))
  hidden_output2 = h2.activate(np.array([input1, input2]))
  final_output = output_neuron.activate(np.array([hidden_output1, hidden_output2]))
  return final_output

input1 = int(input("Enter input 1 (0 or 1): "))
input2 = int(input("Enter input 2 (0 or 1): "))

output = xor_network(input1, input2)
print(f"Input: {input1}, {input2}, Output: {output}")

Enter input 1 (0 or 1): 1
Enter input 2 (0 or 1): 1
Input: 1, 1, Output: 0.8807970779778823


In [9]:
import numpy as np

class Neuron:
    def __init__(self, n_inputs, activation_function):
        self.n_inputs = n_inputs
        self.weights = np.random.rand(n_inputs)
        self.bias = np.random.rand(1)
        self.activation_function = activation_function

    def forward_pass(self, inputs):
        weighted_sum = np.dot(inputs, self.weights) + self.bias
        output = self.activation_function(weighted_sum)
        return output

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def relu(self, x):
        return np.maximum(x, 0)

    def tanh(self, x):
        return np.tanh(x)

neuron = Neuron(n_inputs=2, activation_function=lambda x: neuron.sigmoid(x))

neuron_relu = Neuron(n_inputs=2, activation_function=lambda x: neuron_relu.relu(x))

neuron_tanh = Neuron(n_inputs=2, activation_function=lambda x: neuron_tanh.tanh(x))

inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

outputs_sigmoid = neuron.forward_pass(inputs)
outputs_relu = neuron_relu.forward_pass(inputs)
outputs_tanh = neuron_tanh.forward_pass(inputs)

print("Sigmoid Output:")
print(outputs_sigmoid)

print("ReLU Output:")
print(outputs_relu)

print("Tanh Output:")
print(outputs_tanh)

Sigmoid Output:
[0.52620477 0.71389789 0.57938276 0.75578649]
ReLU Output:
[0.4037696  1.21869659 0.78617976 1.60110675]
Tanh Output:
[0.05175939 0.183319   0.29078894 0.40785635]
